//
// Created by kouta on 29/10/20.
//

#ifndef ABSTRACT_TERROR_STRIKE_GLFWINITIALIZATION_H
#define ABSTRACT_TERROR_STRIKE_GLFWINITIALIZATION_H

#include "glfw_platform.h"

#endif //ABSTRACT_TERROR_STRIKE_GLFWINITIALIZATION_H
